Name: LightGBM
Description: links LightGBM.
Version: null

Cflags: >
    -I/opt/ac_install/${variant}/include

Libs: >
    -L/opt/ac_install/${variant}/lib
    -Wl,-R/opt/ac_install/${variant}/lib

    -l_lightgbm
