Name: Basic build flags
Description: common flags both for build and for judge
Version: null

Cflags: >
    -std=gnu++23

variant:
    gcc:
        Libs: >
            -lstdc++exp

    clang:
        Cflags: >
            -fuse-ld=lld

            -stdlib=libc++
            -fexperimental-library

            -rtlib=compiler-rt
            -unwindlib=libunwind
