Name: Extra user flags
Description: advanced flags for judge
Version: null

Cflags: >
    -march=native
    -flto=auto

    -fconstexpr-depth=1024

variant:
    gcc:
        Cflags: >
            -fconstexpr-loop-limit=524288
            -fconstexpr-ops-limit=2097152

        Libs: >
            -fopenmp

    clang:
        Cflags: >
            -fconstexpr-steps=524288
