theme: jekyll-theme-dinky

base_raw_url: https://cdn.jsdelivr.net/gh/uni-kakurenbo/AtCoder-Language-Update_2024-11_CXX23_proposal

config:
    gcc: dist/gcc/config.toml
    clang: dist/clang/config.toml

google_analytics: G-4P7TZVC1HV
