theme: jekyll-theme-dinky

base_raw_url: https://cdn.jsdelivr.net/gh/uni-kakurenbo/AtCoder-Language-Update_2024-11_CXX23_proposal

github:
    gcc_path: dist/gcc/config.sh
    clang_path: dist/clang/config.toml

google_analytics: G-4P7TZVC1HV
