language = 'C++23'


name = 'GCC'
version = '14.2.0-4ubuntu2~24.04'


filename = 'Main.cpp'

object = 'a.out'


install = '''${{ref:installer}}'''  # auto-replaced

compile = '''${{ref:builder}}'''  # auto-replaced

execution = ['./a.out']


[[license]]
    name = 'GNU GPL v3'
    url = 'https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Copying.html'


[library.AC-Library]
    version = '1.5.1'
    license = [
        { name = 'CC0 1.0', url = 'https://github.com/atcoder/ac-library/blob/master/LICENSE' }
    ]

[library.Boost]
    version = '1.86.0'
    license = [
        { name = 'BSL 1.0', url = 'https://www.boost.org/LICENSE_1_0.txt' }
    ]

[library.Eigen]
    version = '3.4.0-4'
    license = [
        { name = 'MPL 2.0', url = 'https://www.mozilla.org/en-US/MPL/2.0/' },
    ]

[library.GMP]
    version = '2:6.3.0+dfsg-2ubuntu6'
    license = [
        { name = 'GNU LGPL v3', url = 'https://www.gnu.org/licenses/lgpl-3.0.html' },
        { name = 'GNU GPL v2', url = 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.html' }
    ]

[library.libtorch]
    version = '2.5.1'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/LICENSE'

[[library.libtorch.license]]
    name = 'Earlier BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L8-L50'

[[library.libtorch.license]]
    name = '2-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L53-L103'

[[library.libtorch.license]]
    name = 'Apache License'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L105-L285'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L287-L321'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L324-L360'

[[library.libtorch.license]]
    name = 'BSL 1.0'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L362-L418'

[[library.libtorch.license]]
    name = 'PILLOW-SIMD Software License'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L420-L456'

[[library.libtorch.license]]
    name = '3-Clause BSD'
    url = 'https://github.com/pytorch/pytorch/blob/main/NOTICE#L458-L490'
