name: Expand Template
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
            - test/**
    pull_request:
    workflow_dispatch:
        inputs:
            test-mode:
                description: "Test mode"
                required: true
                default: "normal"
                type: choice
                options:
                    - none
                    - normal
#                     - strict

defaults:
    run:
        shell: bash

concurrency:
    group: |
        test-${{
            startsWith(github.ref_name, 'test') && github.ref_name ||
            github.run_id
        }}
    cancel-in-progress: true

jobs:
    prepare-tools:
        name: Prepare Tools
        runs-on: ${{ vars.RUNNER_IMAGE }}

        outputs:
            cache-primary-key: ${{ steps.load-cached-binary.outputs.cache-primary-key }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Load Cached Binary
              id: load-cached-binary
              uses: actions/cache/restore@v4
              with:
                  path: /opt/ac_tools/
                  key: >
                      tools-${{
                        hashFiles(
                          './.github/workflows/internal/prepare.sh',
                          './.github/workflows/internal/tools/**'
                        )
                      }}
                  restore-keys: tools-

            - name: Build
              run: |
                  set -eu

                  sudo cp -rf /opt/ac_tools/** /usr/bin/

                  ./.github/workflows/internal/prepare.sh

                  which pkg-config dasel jq taplo | xargs -I {} cp {} /opt/ac_tools/

            - name: Cache Binary
              uses: actions/cache/save@v4
              if: (!cancelled()) && steps.load-cached-binary.outputs.cache-hit != 'true'
              with:
                  path: /opt/ac_tools/
                  key: ${{ steps.load-cached-binary.outputs.cache-primary-key }}

    config-matrix:
        name: Configure Matrix
        runs-on: ${{ vars.RUNNER_IMAGE }}

        outputs:
            libraries: ${{ steps.gen-lib-list.outputs.list }}
            execlude-libraries: ${{ steps.gen-lib-list.outputs.execlude }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Generate Library List
              id: gen-lib-list
              run: |
                  set -eu

                  EXCLUDE='["abseil"]'

                  {
                    echo -n "list="
                    {
                      echo -n "["
                      ls ./src/sub-installers/ | sed -e s/^/\"/g -e s/\.sh$/\"/g | tr '\n' ',' | sed s/,$//g
                      echo -n "]"
                    } | jq -c --argjson exclude "${EXCLUDE}" '. - $exclude'
                  } >>"${GITHUB_OUTPUT}"

                  echo "execlude=${EXCLUDE}" >>"${GITHUB_OUTPUT}"

    gen-installer:
        name: Generate Installers
        needs: prepare-tools
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Load Cached Tools
              uses: actions/cache/restore@v4
              with:
                  path: /opt/ac_tools/
                  key: tools-${{ needs.prepare-tools.outputs.cache-primary-key }}

            - name: Apply Tools
              run: sudo cp -rf /opt/ac_tools/** /usr/bin/

            - name: Expand
              run: |
                  set -eu

                  sudo rm -rf ./dist/ && mkdir -p ./dist/
                  ./.github/workflows/internal/expanders/installer.sh

                  if [ -f ./dist/install.sh ]; then
                    {
                      echo '# `install.sh`'
                      echo '```bash'
                      cat ./dist/install.sh
                      echo '```'
                    } >> "${GITHUB_STEP_SUMMARY}"
                  fi

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: dist-installers
                  path: ./dist/

    install:
        name: Install Libraries
        needs:
            - prepare-tools
            - gen-installer
            - config-matrix

        runs-on: ${{ vars.RUNNER_IMAGE }}

        strategy:
            matrix:
                target: ${{ fromJson(needs.config-matrix.outputs.libraries) }}
            fail-fast: false

        steps:
            # - name: Collect Workflow Telemetry
            #   uses: catchpoint/workflow-telemetry-action@v2
            #   with:
            #       theme: dark

            - name: Configure Installation
              run: |
                  set -eu

                  TARGET='${{ matrix.target }}'

                  LIBRARIES='${{ needs.config-matrix.outputs.libraries }}'
                  EXECLUDE_LIBRARIES='${{ needs.config-matrix.outputs.execlude-libraries }}'

                  echo "${LIBRARIES}" | jq -c -r '.[]' |
                    while read -r lib_id; do
                      if [ "${TARGET}" != "${lib_id}" ]; then
                        echo "AC_NO_BUILD_${lib_id//-/_}=true" >>"${GITHUB_ENV}"
                      fi
                    done

                  echo "${EXECLUDE_LIBRARIES}" | jq -c -r '.[]' |
                    while read -r lib_id; do
                        echo "AC_NO_BUILD_${lib_id//-/_}=true" >>"${GITHUB_ENV}"
                    done

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Download Installers
              uses: actions/download-artifact@v4
              with:
                  name: dist-installers
                  path: ./dist/

            - name: Load Cached Tools
              uses: actions/cache/restore@v4
              with:
                  path: /opt/ac_tools/
                  key: tools-${{ needs.prepare-tools.outputs.cache-primary-key }}

            - name: Apply Tools
              run: sudo cp -rf /opt/ac_tools/** /usr/bin/

            - name: Load CCache
              if: ${{ github.event.inputs.test-mode != 'strict' }}
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true
                  append-timestamp: false
                  key: >
                      cache-${{ matrix.target }}-${{
                        hashFiles(
                          './src/install.sh',
                          './src/install.toml',
                          './config/internal/ac_basic.pc',
                          './config/internal/ac_internal.pc',
                          format('./src/sub-installers/{0}.sh', matrix.target),
                          format('./config/library/ac_{0}.pc', matrix.target)
                        )
                      }}
                  restore-keys: cache-${{ matrix.target }}-

            - name: Install
              env:
                  TARGET: ${{ matrix.target }}
                  RUN_TEST: ${{ github.event.inputs.test-mode == 'strict' }}
              run: |
                  set -eu

                  chmod +x ./dist/install.sh
                  ./dist/install.sh

                  find /tmp/ac_install/ -iname *.tar.* -or -iname *.zip -print0 |
                    xargs -0 -I {} sudo rm -rf {}

            - name: Collect Pkgconfig Files
              run: |
                  set -eu

                  mkdir -p ./config/libs/
                  find /opt/ac_install/ -name '*.pc' -type f -print0 |
                    xargs -0 -I {} sudo cp {} ./config/libs/

            - name: Upload Pkgconfig Files
              uses: actions/upload-artifact@v4
              with:
                  name: pkgconfig-${{ matrix.target }}
                  path: ./config/libs/

            - name: Clean Up
              run: |
                  set -eu

                  find /opt/ac_install/ -name cmake -or -name pkgconfig -or -name bin -or -name share -type d -print0 |
                    xargs -0 sudo rm -rf

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: library-${{ matrix.target }}
                  path: /opt/ac_install/
                  compression-level: 9

    gen-compiler:
        name: Generate Compiler
        needs:
            - prepare-tools
            - install
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Load Cached Tools
              uses: actions/cache/restore@v4
              with:
                  path: /opt/ac_tools/
                  key: tools-${{ needs.prepare-tools.outputs.cache-primary-key }}

            - name: Apply Tools
              run: sudo cp -rf /opt/ac_tools/** /usr/bin/

            - name: Download Pkgconfig Files
              uses: actions/download-artifact@v4
              with:
                  pattern: pkgconfig-*
                  path: ./config/libs/
                  merge-multiple: true

            - name: Expand
              run: |
                  set -eu

                  sudo rm -rf ./dist/ && mkdir -p ./dist/
                  ./.github/workflows/internal/expanders/compiler.sh

                  if [ -f ./dist/compile.sh ]; then
                    {
                      echo '# `compile.sh`'
                      echo '```bash'
                      cat ./dist/compile.sh
                      echo '```'
                    } >> "${GITHUB_STEP_SUMMARY}"
                  fi

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: dist-compiler
                  path: ./dist/

    test:
        name: Test
        needs: gen-compiler
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Download Libraries
              uses: actions/download-artifact@v4
              with:
                  pattern: library-*
                  path: /opt/ac_install/
                  merge-multiple: true

            - name: Download Compiler
              uses: actions/download-artifact@v4
              with:
                  name: dist-compiler
                  path: ./dist/

            - name: Test
              if: github.event.inputs.test-mode != 'none'
              run: ./.github/workflows/internal/test.sh

    gen-config:
        name: Generate Configuration File
        needs:
            - prepare-tools
            - gen-compiler
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Load Cached Tools
              uses: actions/cache/restore@v4
              with:
                  path: /opt/ac_tools/
                  key: tools-${{ needs.prepare-tools.outputs.cache-primary-key }}

            - name: Apply Tools
              run: sudo cp -rf /opt/ac_tools/** /usr/bin/

            - name: Download Installer
              uses: actions/download-artifact@v4
              with:
                  pattern: dist-*
                  path: ./dist/
                  merge-multiple: true

            - name: Expand Configuration File
              run: |
                  set -eu

                  ./.github/workflows/internal/expanders/config.sh

                  if [ -f ./dist/install.toml ]; then
                    {
                      echo '# `install.toml`'
                      echo '```toml'
                      cat ./dist/install.toml
                      echo '```'
                    } > "${GITHUB_STEP_SUMMARY}"
                  fi

            - name: Lint
              run: ./.github/workflows/internal/lint.sh

            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  name: dist-config
                  path: ./dist/

    push:
        name: Push to Repository
        needs: [gen-config, test]
        if: (!cancelled()) && github.ref_name == 'main'
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY }}

            - name: Download Installers
              uses: actions/download-artifact@v4
              with:
                  pattern: dist-*
                  path: ./dist/
                  merge-multiple: true

            - name: Push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -eu

                  git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

                  git config --global user.name "Template Expander"
                  git config --global user.email "noreply@example.com"

                  git add -f ./dist/

                  if (git diff --cached --shortstat | grep '[0-9]'); then
                    git commit -m "[workflow] expand templates ${GITHUB_SHA}"

                    REPOSITORY_NAME="${{ github.head_ref || github.ref_name }}"

                    git pull --rebase origin "${REPOSITORY_NAME}"
                    git push origin "HEAD:${REPOSITORY_NAME}"
                  else
                    echo "No updated files."
                  fi
