name: Expand template
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: expand-${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    replace:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0
                  ssh-key: ${{ secrets.SSH_KEY }}

            - name: Replace template
              run: ./.github/workflows/internal/replace.sh

            - name: Push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  set -eu

                  git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git

                  git config --global user.name "Template Expander"
                  git config --global user.email "noreply@example.com"

                  git add -f ./dist/

                  if (git diff --cached --shortstat | grep '[0-9]'); then
                    git commit -m "[workflow] expand install.toml template ${GITHUB_SHA}"

                    REPOSITORY_NAME="${{ github.head_ref || github.ref_name }}"

                    git pull --rebase origin "${REPOSITORY_NAME}"
                    git push origin "HEAD:${REPOSITORY_NAME}"
                  else
                    echo "No updated files."
                  fi
