name: Generate Pages
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    workflow_dispatch:

    push:
        branches:
            - main

        paths:
            - pages/**

    workflow_run:
        workflows: ["Expand Templates", "Run Test within A Docker Container"]
        types: [completed]
        branches: [main]

defaults:
    run:
        shell: bash

concurrency:
    group: pages-${{ github.repository_id }}
    cancel-in-progress: true

jobs:
    configure:
        name: Configure
        if: ${{ !github.event.workflow_run.conclusion || github.event.workflow_run.conclusion == 'success' }}
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Configure
              uses: actions/configure-pages@v4

    build:
        name: Build
        needs: configure
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Dump data
              run: |
                  ./.github/workflows/internal/dump.sh >>./pages/index.md

            - name: Build with Jekyll
              uses: actions/jekyll-build-pages@v1
              with:
                  source: ./pages/

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3

    deploy:
        name: Deploy
        needs: build
        runs-on: ${{ vars.RUNNER_IMAGE }}

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        permissions:
            contents: write
            pages: write
            id-token: write

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
