name: Run test
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    pull_request:
    workflow_dispatch:

jobs:
    run:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0

            - name: Replace template
              run: ./.github/workflows/internal/replace.sh

            - name: Install
              run: |
                  chmod +x ./dist/install.sh
                  ./dist/install.sh

            - name: Clean-up
              run: rm -rf ./tmp/

            - name: Run test
              run: ./.github/workflows/internal/test.sh
