name: Run Test within A Docker Container
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Expand Templates"]
        types: [completed]
        branches: [main]

defaults:
    run:
        shell: bash

concurrency:
    group: test-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true

jobs:
    run:
        name: Run
        if: ${{ !github.event.workflow_run.conclusion || github.event.workflow_run.conclusion == 'success' }}
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - name: Collect Workflow Telemetry
              uses: catchpoint/workflow-telemetry-action@v2
              with:
                  theme: dark
                  comment_on_pr: false
                  proc_trace_sys_enable: false

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Download Tester
              uses: actions/checkout@v4
              with:
                  repository: tatyam-prime/ALU2024_Dockerfile
                  path: ./.test-runner/

            - name: Run
              working-directory: ./.test-runner/
              run: |
                  set -eu

                  cat ../dist/config.toml >./installscript.toml
                  cp ../test/00_plane/0000.test.cpp src/source

                  python3 src/parse.py
                  docker build --platform linux/amd64 -t atcoder -f src/Dockerfile .

                  docker run --rm -it atcoder
