name: Run test
run-name: ${{ github.workflow }} (${{ github.ref_name }})

on:
    push:
        branches:
            - main
            - test/**
    pull_request:
    workflow_dispatch:
        inputs:
            test-mode:
                required: true
                default: "normal"
                type: choice
                options:
                    - none
                    - normal
                    - strict

concurrency:
    group: |
        test-${{
            startsWith(github.ref_name, 'test') && github.ref_name ||
            github.run_id
        }}
    cancel-in-progress: true

jobs:
    run:
        runs-on: ${{ vars.RUNNER_IMAGE }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref_name }}
                  fetch-depth: 0

            - name: Use ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  create-symlink: true

            - name: Replace template
              run: ./.github/workflows/internal/replace.sh

            - name: Install
              env:
                  RUN_TEST: ${{ github.event.inputs.test-mode == 'strict' }}
              run: |
                  chmod +x ./dist/install.sh
                  ./dist/install.sh

            - name: Run test
              if: ${{ github.event.inputs.test-mode != 'none' }}
              run: ./.github/workflows/internal/test.sh
